workflows:
  ios-hls-prototype:
    name: iOS HLS Prototype Build
    max_build_duration: 60
    environment:
      xcode: latest

    scripts:
      - name: Clean & Build iOS App (unsigned)
        script: |
          echo "🧹 Cleaning old build artifacts..."
          rm -rf build
          echo "🚀 Building iOS app (unsigned)..."
          xcodebuild \
            -project ios-hls-player-prototyp.xcodeproj \
            -scheme ios-hls-player-prototyp \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build \
            -derivedDataPath $CM_BUILD_DIR/build

    artifacts:
      - build/Build/Products/Release-iphoneos/*.app

    publishing:
      email:
        recipients:
          - devashishmushrif@gmail.com
