workflows:
  ios-hls-prototype:
    name: iOS HLS Prototype Build
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "ios-hls-player-prototyp.xcodeproj"
        XCODE_SCHEME: "ios-hls-player-prototyp"
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          cd $CM_BUILD_DIR
          echo "✅ Checking Xcode project..."
          ls
          echo "✅ Installing dependencies (if any)"
          pod install || echo "No Podfile found, skipping..."

      - name: Build iOS App
        script: |
          echo "🚀 Building iOS app..."
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build

      - name: List build output
        script: |
          echo "📁 Listing generated files..."
          find $CM_BUILD_DIR -type f -iname "*.app" -o -iname "*.ipa" || echo "No app/ipa found"

    artifacts:
      - build/Release-iphoneos/*.app
      - build/Release-iphoneos/*.ipa
      - $CM_BUILD_DIR/build/Release-iphoneos/*.app
      - $CM_BUILD_DIR/build/Release-iphoneos/*.ipa

    publishing:
      email:
        recipients:
          - devashishmushrif@gmail.com
