workflows:
  ios-hls-prototype:
    name: iOS HLS Prototype Build
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "ios-hls-player-prototyp.xcodeproj"
        XCODE_SCHEME: "ios-hls-player-prototyp"
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          cd $CM_BUILD_DIR
          echo "✅ Checking Xcode project..."
          ls
          echo "✅ Installing dependencies (if any)"
          pod install || echo "No Podfile found, skipping..."

      - name: Build & Archive iOS App
        script: |
          echo "🚀 Archiving iOS app for IPA export..."
          xcodebuild \
            -project "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build/$XCODE_SCHEME.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            archive

          echo "📦 Exporting IPA..."
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build/$XCODE_SCHEME.xcarchive \
            -exportPath $CM_BUILD_DIR/build/ipa \
            -exportOptionsPlist <(echo '<?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" 
            "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
              <key>method</key><string>ad-hoc</string>
              <key>compileBitcode</key><false/>
              <key>destination</key><string>export</string>
              <key>signingStyle</key><string>manual</string>
              <key>stripSwiftSymbols</key><true/>
            </dict>
            </plist>')

    artifacts:
      - build/ipa/*.ipa
      - build/Release-iphoneos/*.app

    publishing:
      email:
        recipients:
          - devashishmushrif@gmail.com
